version: "3"

networks:
  ms-bridge:
    external: true

volumes:
  database_postgres:

services:
  postgres:
    container_name: "postgres"
    restart: always
    image: postgres:latest
    networks: 
      - ms-bridge
    volumes: 
      - database_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"

  user-service:
    container_name: "user-service"
    build: ./user-service
    restart: on-failure
    ports: 
      - "8090:8090"
    networks: 
      - ms-bridge
    depends_on:
      - postgres

  order-service:
    container_name: "order-service"
    build: ./order-service
    restart: on-failure
    networks: 
      - ms-bridge
    depends_on: 
      - postgres